Update setup.py
python_requires="<3.0",

changed to

python_requires=">2.6",

in order to solve this error:

Collecting py2pdf
  Using cached py2pdf-0.0.tar.gz (5.6 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
INFO: pip is looking at multiple versions of py2pdf to determine which version is compatible with other requirements. This could take a while.

ERROR: Package 'py2pdf' requires a different Python: 3.10.6 not in '<3.0'